### ISSUE TITLE
broken on node 8

### ISSUE THREAD

**Issue by 75lb** [MorrisLLC/grunt-war#21]
I'm getting errors when running `grunt war` on node 8. It works fine on v7. This is the output: 

```
$ grunt war --stack
Running "war:dist" (war) task
Fatal error: Cannot read property 'pipesCount' of undefined
TypeError: Cannot read property 'pipesCount' of undefined
  at module.exports.Readable.pipe (_stream_readable.js:545:16)
  at module.exports.ZipArchiveOutputStream._smartStream (/Users/lloydb/Documents/objective/ecc-ui/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
  at module.exports.ZipArchiveOutputStream._appendBuffer (/Users/lloydb/Documents/objective/ecc-ui/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:82:10)
  at module.exports.ArchiveOutputStream.entry (/Users/lloydb/Documents/objective/ecc-ui/node_modules/compress-commons/lib/archivers/archive-output-stream.js:86:10)
  at module.exports.ZipStream.entry (/Users/lloydb/Documents/objective/ecc-ui/node_modules/zip-stream/index.js:138:49)
  at Zip.append (/Users/lloydb/Documents/objective/ecc-ui/node_modules/archiver/lib/plugins/zip.js:53:15)
  at Archiver._moduleAppend (/Users/lloydb/Documents/objective/ecc-ui/node_modules/archiver/lib/core.js:172:16)
  at Archiver._onQueueTask (/Users/lloydb/Documents/objective/ecc-ui/node_modules/archiver/lib/core.js:370:8)
  at /Users/lloydb/Documents/objective/ecc-ui/node_modules/archiver/node_modules/async/dist/async.js:4045:9
  at process (/Users/lloydb/Documents/objective/ecc-ui/node_modules/archiver/node_modules/async/dist/async.js:2316:17)
  at Immediate._onImmediate (/Users/lloydb/Documents/objective/ecc-ui/node_modules/archiver/node_modules/async/dist/async.js:66:16)
  at runCallback (timers.js:800:20)
  at tryOnImmediate (timers.js:762:5)
  at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by wibobm** [comment]
I'll check into this tonight and fix.   Thank you.
